== Pangramy a citáty

Kusy textu, které sem dávám jenom abych mohl testovat hledání nově přidaným vyhledávačem na nějakém trochu reálném textu. Je tu prostý text, text v citátu a formátovaná báseň. Tak schválně co to udělá s tím offline vyhledávačem, který se mi sem povedlo implementovat. 

=== Slovenský pangram

Vypätá dcéra grófa Maxwella s IQ nižším ako kôň núti čeľaď hrýzť hŕbu jabĺk.

=== Můj oblíbený český pangram

Nechť již hříšné saxofony ďáblů rozezvučí síň úděsnými tóny waltzu, tanga a quickstepu.

=== Náhodný citát

[quote, James T. Kirk, Star Trek: Generations]
Kdo jsem já, abych se hádal s kapitánem Enterprise?

=== Pangramová báseň

[verse, česká pangramová báseň]
V přílivu žluťoučkých květů včelky se vznášejí.
Hleď, toť čarovný je loužek, kde hedvábné štěstíčka září.
Vodní žíňky běží kolem lesní tůně a kadeřemi svými čeří stříbrosvit měsíce.
Qvído, kouzelníkův učeň s ďolíčky utírá prach z vílích křídel.
Ó, náhlý úsvit oblažil zemětvář prolínajícím hřejivým dotekem svým.
